language: node_js

node_js:
  - 9
addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

install:
  - yarn install
  - yarn add cypress

before_script:
  - yarn start -- --silent &

script:
  - yarn build
  - yarn run cypress:run
  - yarn test
